### ISSUE TITLE
Analysis throws error "statistics.StatisticsError: variance requires at least two data points"

### ISSUE THREAD

**Issue by aufbakanleitung** [llu13701/sms_analysis#3]
```bash
/usr/local/bin/python3.9 /Users/xxx/code/persoonlijk/sms_analysis/simple_stats.py
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForNextSentencePrediction: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForNextSentencePrediction from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

Enter your whatapp chat filename (ending in txt): WhatsApp-chat met xxx.txt
Please enter your whatsapp name: Xxxx
try whatsapp processing
file date_format is  %d/%m/%y, %I:%M:%S %p
try messenger processing
date_format for the file is  %d/%m/%y, %I:%M:%S %p
something is wrong with the file
cleaning messanger data
finish processing

Traceback (most recent call last):
  File "/Users/xxx/code/persoonlijk/sms_analysis/simple_stats.py", line 508, in <module>
    stats_collections()
  File "/Users/xxx/code/persoonlijk/sms_analysis/simple_stats.py", line 485, in stats_collections
    generate_master_summary(pd_text)
  File "/Users/xxx/code/persoonlijk/sms_analysis/simple_stats.py", line 283, in generate_master_summary
    custom_stopwords=identify_custom_stopwords(list_of_entire_text)
  File "/Users/xxx/code/persoonlijk/sms_analysis/incoming_outgoing_msg.py", line 52, in identify_custom_stopwords
    one_stdev=statistics.mean(diff)-0.7*statistics.stdev(diff)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/statistics.py", line 797, in stdev
    var = variance(data, xbar)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/statistics.py", line 739, in variance
    raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points

Process finished with exit code 1
```

**Comment by aufbakanleitung** [comment]
Could it perhaps have something to do with the language difference? I just noticed that Whatsapp fills in certain thing in Dutch:
```
27-12-2020 09:25 - Herman: <Media weggelaten>
27-12-2020 09:25 - DCI: Haha cute
31-12-2020 21:22 - Herman: <Media weggelaten>
```

**Comment by llu13701** [comment]
Oh yeah, this thing does not work in Dutch!! Sorry about that. The stats on
sentiment and initiation will be wrong!

**Comment by aufbakanleitung** [comment]
Our conversation is in English though. Though I did just notice it says `file date_format is`:
`%d/%m/%y, %I:%M:%S %p`
But it's actually:
`%d-%m-%y %I:%M`

Could that be the problem?

**Comment by llu13701** [comment]
Huh are you sure about %d-%m-%y %I:%M.. usually its %H:%M or %I:%M %p

**Comment by aufbakanleitung** [comment]
Ah no, above I have an excerpt: `31-12-2020 21:22 - Herman:`
I'm not sure about the notation though, I usually use `dd-mm-yyyy HH:MM -`

So I guess you're right, the %I should be %H
